<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<!-- Display success message when new entry is saved in the database -->
		@if (Session::has('success'))
			<div class="alert alert-success alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				{{ Session::get('success') }}
			</div>
		@endif
		@if (Session::has('danger'))
			<div class="alert alert-danger alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				{{ Session::get('danger') }}
			</div>
		@endif
		@if (Session::has('info'))
			<div class="alert alert-info alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				{{ Session::get('info') }}
			</div>
		@endif

		<!-- Display error messages generated by the system -->
		{{-- @if (count($errors) > 0)
			<div class="alert alert-danger alert-dismissible" role="alert">
				<strong>The following errors have occured:</strong>
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<ul>
					@foreach ($errors->all() as $error)
						<li> {{ $error }} </li>
					@endforeach
				</ul>
			</div>
		@endif --}}
	</div>
</div>